bommer_blog:
    resource: "@BommerBlogBundle/Resources/config/routing.yml"
    prefix:   /

ens_jobeet:
    resource: "@EnsJobeetBundle/Resources/config/routing.yml"
    prefix:   /

blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

