blogger_blog_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Default:index }
    requirements:
        _method:  GET
        
blogger_blog_about:
    pattern:  /about/
    defaults: { _controller: BloggerBlogBundle:Default:about }
    requirements:
        _method:  GET